#!/usr/bin/env python3

# Scan all subdirectories of src, interpret them as chapters and write 
# chapters.tex to include all of these chapters. Additionally, a file for every 
# subdirectory is added in src to define the chapter in latex and include the 
# files in the according chapter directory. This way, building the document via 
# makefile will always automatically include every new file if there is one on a 
# tool or feature that had no type of documentation or note to this point.
#
# Handling chapters and chapter names:
# * There needs to be a text file "chapter_order", denoting the chapter order 
# one chapter per row. (Currently,) every chapter must be in chapter_order. Same 
# story for appendix_order.
# * chapter names: chapter titles are set exactly the way they appear in 
# chapter_order. directory and file name are all lower-case, and whitespaces get 
# filled with underscores.
# EXAMPLE
# * chapter_order: "MY Chapter"
# * title: "MY Chapter"
# * directory: "src/[appendix/]my_chapter"
# * file: "src/[appendix/]my_chapter.tex"
# The point here is to be able to set the titles as you want, but have all 
# lower-case directory and file names.
# TODO: handle all lower-case words in chapter name, like "and"
#
# TODO: for reports (which have sections, not chapters), this script should have 
# a way of still including everything, but not making things a chapter.

import os
import glob

FILE_CHAPTERS_TEX = "chapters.tex"


def str_to_title(string):
    '''
    In principle just take the string and capitalize the first letter (as 
    directory names are nicer if written non-capitalized and the chapter names 
    are taken from the list of src directories). Can also handle multi-word 
    strings: "first_chapter" -> "First Chapter"
    '''

    list_string = string.split('_')
    title = " ".join(
#             [s[0].capitalize() + s[1:] if not s.isupper() else s for s in list_string])
            [s.capitalize() if not s.isupper() else s for s in list_string])

    return title


def title_to_basename(string):
    '''
    Turn a chapter title into all lower-case, and whitespace to underscore, for 
    directory and file name.
    '''
    list_string = string.split(' ')
    basename = "_".join([s.lower() for s in list_string])
    
    return basename


def write_chapter_file(chapter_title, subdir=""):
    if not subdir:
        path_top = "src"
    else:
        path_top = os.path.join("src", subdir)

    chapter_basename =title_to_basename(chapter_title)

    path_chapter = os.path.join(path_top, chapter_basename)

    with open(f"{path_top}/{chapter_basename}.tex", 'w') as f_chapter:
        f_chapter.write(
r"""% !!! This file has been automatically generated by include_chapters.py. Do not 
% edit it because your edits are very likely to soon be overwritten !!!

\chapter{""" + chapter_title + r"""}
\label{cha:""" + chapter_basename + """}

""")

        files_sections = glob.glob(f"{path_chapter}/*.tex")
        files_sections.sort()
        for file_section in files_sections:
            f_chapter.write(r"\input{" + file_section+ "}\n")


def write_chapter_include_file(l_chapter_title, subdir="", file_out=FILE_CHAPTERS_TEX):
    """
    :subdir: if given, file include command will be
        `\input{src/<subdir>/<chapter_basename>.tex}` for <chapter> in <chapters>
        (otherwise the `<subdir>/` part is skipped)
    """
    if subdir:
        include_path = os.path.join("src", subdir)
    else:
        include_path = "src"

    with open(file_out, 'w') as f_chapters:
        f_chapters.write(
"""% !!! This file has been automatically generated by include_chapters.py. Do not 
% edit it because your edits are very likely to soon be overwritten !!!

""")

        for chapter_title in l_chapter_title:
            chapter_basename = title_to_basename(chapter_title)
            f_chapters.write(r"\input{" + include_path + "/" + chapter_basename + ".tex}\n")


def main():

    ##############################
    # MAIN DOCUMENT
    ##############################

    # DETECT CHAPTERS
    chapters_unordered = [ch for ch in os.listdir("src") if \
                os.path.isdir(f"src/{ch}") and not ch.lower() == "appendix"]

    # FINAL CHAPTER LIST IN ORDER
    # 1. take every entry from the order file as the first chapters
    # 2. if any detected chapters are left, append them to the chapter list in 
    # whatever order
    with open("chapter_order", 'r') as f_chapter_order:
        chapters = f_chapter_order.readlines()
        chapters = [s.removesuffix('\n') for s in chapters]

#     remaining_chapters = [chapter for chapter in chapters_unordered if chapter
#                           not in chapters]
#     if remaining_chapters:
#         chapters.append(*remaining_chapters)

    # TOP-LEVEL TEX FILES
    # write chapter top-level tex files
    print(chapters)
    for chapter in chapters:
        write_chapter_file(chapter)

    # CHAPTER INCLUDE FILE
    # write chapter include file
    write_chapter_include_file(chapters)

    ##############################
    # APPENDIX
    ##############################
    # most of the steps are almost the same, just with different filtering and 
    # some adjusted paths

    # DETECT CHAPTERS
    appendix_unordered = []
    if os.path.isdir("src/appendix"):
        appendix_unordered = [ch for ch in os.listdir("src/appendix") if \
                                    os.path.isdir(f"src/appendix/{ch}")]

    # FINAL CHAPTER LIST IN ORDER
    # 1. take every entry from the order file as the first chapters
    # 2. if any detected chapters are left, append them to the chapter list in 
    # whatever order
    with open("appendix_order", 'r') as f_appendix_order:
        chapters = f_appendix_order.readlines()
        chapters = [s.removesuffix('\n') for s in chapters]

#     remaining_chapters = [chapter for chapter in appendix_unordered if chapter
#                           not in chapters]
#     if remaining_chapters:
#         chapters.append(remaining_chapters)

    # TOP-LEVEL TEX FILES
    # write chapter top-level tex files
    print(chapters)
    for chapter in chapters:
        write_chapter_file(chapter, subdir="appendix")

    # CHAPTER INCLUDE FILE
    # write chapter include file
    write_chapter_include_file(chapters, subdir="appendix", file_out="appendix.tex")


if __name__ == "__main__":
    main()
